### ISSUE TITLE
Peer-to-peer code review team 161

### ISSUE THREAD

**Issue by abongsjoel** [rebeccayilma/NYT_article#3]
This issue is created for one of the code reviews of one of the team members  (Alexis) of team 161

**Comment by abongsjoel** [comment]
For grid-template-columns, rather than using percentage values, try to make use of auto and fr instead

**Comment by MrkarlosM** [comment]
Don't forget to give a descriptive name to the `alt` attribute. 

It is a good practice to create a single div for all the Cards you are showing on the bottom side of the page.

**Comment by MrkarlosM** [comment]
Remember to set all the default margins to zero.

Also, you could look for this video to know how to implement a Reset CSS file to your project.

[https://www.youtube.com/watch?v=14Vb6tZCjEY](url)
